[package]
name = "bytebit/destroyed-instance-logging"
description = "Just a simple set of functions for making consistent destroyed instance logs."
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
